### PR TITLE
Added support for latest Redis production version, 3.2.1 

### PR DESCRIPTION
**Pull request by donbeave**

### CODE REVIEW

**Comment by michaelmosmann** [comment]
Can you fix the gradle-setup instead of deleting it? or leave it as it is, so that we can fix this later?

**Comment by donbeave** [comment]
@michaelmosmann ok, I will fix Gradle setup.

**Comment by donbeave** [comment]
Done.

**Comment by matlockx** [comment]
lgtm

**Comment by michaelmosmann** [comment]
Me too.. @martin: can you pull?

Am 30. Juli 2016 15:57:06 MESZ, schrieb "Martin Jöhren" <notifications@github.com>:
>lgtm
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/flapdoodle-oss/de.flapdoodle.embed.redis/pull/8#issuecomment-236366605

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matlockx** [comment]
Thanks a lot for your contribution!

**Comment by donbeave** [comment]
Btw, what about switch build system to Gradle only? I don't think Maven is still necessary.

And can I do code-format for all project?

And the last question, at our company we use this library for our integration tests, I can maintain it in future, if it's okey with you guys.

**Pull request merged**
